#include "Animations.hpp"

namespace Stand
{
	const std::vector<SimpleAnimation> Animations::scenarios = {
		{ LOC("ANIM1"), "WORLD_HUMAN_MUSCLE_FLEX"},
		{ LOC("ANIM2"), "WORLD_HUMAN_SMOKING" },
		{ LOC("ANIM3"), "WORLD_HUMAN_BUM_SLUMPED" },
		{ LOC("ANIM4"), "WORLD_HUMAN_CHEERING" },
		{ LOC("ANIM5"), "WORLD_HUMAN_GUARD_STAND" },
		{ LOC("ANIM6"), "WORLD_HUMAN_HAMMERING" },
		{ LOC("ANIM7"), "WORLD_HUMAN_COP_IDLES" },
		{ LOC("ANIM8"), "PROP_HUMAN_BUM_BIN" },
		{ LOC("ANIM9"), "WORLD_HUMAN_MOBILE_FILM_SHOCKING" },
		{ LOC("ANIM10"), "WORLD_HUMAN_HANG_OUT_STREET" },
		{ LOC("ANIM11"), "WORLD_HUMAN_STAND_IMPATIENT" },
		{ LOC("ANIM12"), "WORLD_HUMAN_STAND_MOBILE" },
		{ LOC("ANIM94"), "WORLD_HUMAN_LEANING" },
		{ LOC("ANIM14"), "CODE_HUMAN_MEDIC_TEND_TO_DEAD" },
		{ LOC("ANIM15"), "CODE_HUMAN_CROSS_ROAD_WAIT" },
		{ LOC("ANIM16"), "WORLD_HUMAN_MAID_CLEAN" },
		{ LOC("ANIM17"), "PROP_HUMAN_ATM" },
		{ LOC("ANIM18"), "WORLD_HUMAN_YOGA" },
		{ LOC("ANIM19"), "WORLD_HUMAN_HUMAN_STATUE" },
		{ LOC("ANIM20"), "WORLD_HUMAN_WELDING" },
		{ LOC("ANIM21"), "WORLD_HUMAN_SUNBATHE_BACK" },
		{ LOC("ANIM22"), "WORLD_HUMAN_SUNBATHE" },
		{ LOC("ANIM23"), "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS" },
		{ LOC("ANIM24"), "WORLD_HUMAN_PROSTITUTE_LOW_CLASS" },
		{ LOC("ANIM25"), "CODE_HUMAN_MEDIC_TIME_OF_DEATH" },
		{ LOC("ANIM26"), "CODE_HUMAN_MEDIC_KNEEL" },
		{ LOC("ANIM27"), "WORLD_HUMAN_JOG_STANDING" },
		{ LOC("ANIM28"), "WORLD_HUMAN_BINOCULARS" },
		{ LOC("ANIM29"), "WORLD_HUMAN_BUM_STANDING" },
		{ LOC("ANIM30"), "WORLD_HUMAN_GARDENER_PLANT" },
		{ LOC("ANIM31"), "WORLD_HUMAN_PICNIC" },
		{ LOC("ANIM32"), "WORLD_HUMAN_STAND_FISHING" },
		{ LOC("ANIM33"), "WORLD_HUMAN_WINDOW_SHOP_BROWSE" },
		{ LOC("ANIM34"), "PROP_HUMAN_SEAT_BENCH" },
	};

	const std::vector<ComplexAnimation> Animations::animations = {
		{ LOC("ANIM55"), "mp_player_inteat@pnq", "loop"},
		{ LOC("ANIM56"), "anim@mp_fm_event@intro", "beast_transform" },
		{ LOC("ANIM57"), "switch@trevor@scares_tramp", "trev_scares_tramp_idle_tramp" },
		{ LOC("ANIM58"), "switch@trevor@annoys_sunbathers", "trev_annoys_sunbathers_loop_girl" },
		{ LOC("ANIM59"), "missfbi3_sniping", "prone_dave" },
		{ LOC("ANIM60"), "misscarsteal3pullover", "pull_over_right" },
		{ LOC("ANIM15"), "amb@world_human_hang_out_street@female_hold_arm@idle_a", "idle_a" },
		{ LOC("ANIM62"), "random@drunk_driver_1", "drunk_driver_stand_loop_dd1" },
		{ LOC("ANIM63"), "random@drunk_driver_1", "drunk_driver_stand_loop_dd2" },
		{ LOC("ANIM64"), "missarmenian2", "standing_idle_loop_drunk" },
		{ LOC("ANIM65"), "anim@mp_player_intcelebrationfemale@air_guitar", "air_guitar" },
		{ LOC("ANIM66"), "anim@mp_player_intcelebrationfemale@air_synth", "air_synth" },
		{ LOC("ANIM67"), "misscarsteal4@actor", "actor_berating_loop" },
		{ LOC("ANIM68"), "oddjobs@assassinate@vice@hooker", "argue_a" },
		{ LOC("ANIM69"), "anim@amb@clubhouse@bar@drink@idle_a", "idle_a_bartender" },
		{ LOC("ANIM70"), "anim@mp_player_intcelebrationfemale@blow_kiss", "blow_kiss" },
		{ LOC("ANIM71"), "anim@mp_player_intcelebrationpaired@f_f_sarcastic", "sarcastic_left" },
		{ LOC("ANIM72"), "misscommon@response", "bring_it_on" },
		{ LOC("ANIM73"), "mini@triathlon", "want_some_of_this" },
		{ LOC("ANIM75"), "amb@code_human_police_investigate@idle_a", "idle_b" },
		{ LOC("ANIM74"), "anim@amb@nightclub@peds@", "rcmme_amanda1_stand_loop_cop" },
		{ LOC("ANIM76"), "amb@world_human_hang_out_street@female_arms_crossed@idle_a", "idle_a" },
		{ LOC("ANIM77"), "anim@amb@nightclub@peds@", "rcmme_amanda1_stand_loop_cop" },
		{ LOC("ANIM78"), "gestures@m@standing@casual", "gesture_damn" },
		{ LOC("ANIM79"), "anim@am_hold_up@male", "shoplift_mid" },
		{ LOC("ANIM81"), "anim@mp_player_intcelebrationfemale@face_palm", "face_palm" },
		{ LOC("ANIM82"), "random@car_thief@agitated@idle_a", "agitated_idle_a" },
		{ LOC("ANIM83"), "random@drunk_driver_1", "drunk_fall_over" },
		{ LOC("ANIM84"), "mp_sleep", "sleep_loop" },
		{ LOC("ANIM85"), "random@train_tracks", "idle_e" },
		{ LOC("ANIM86"), "timetable@reunited@ig_2", "jimmy_getknocked" },
		{ LOC("ANIM26"), "rcmextreme3", "idle" },
		{ LOC("ANIM88"), "timetable@jimmy@doorknock@", "knockdoor_idle" },
		{ LOC("ANIM89"), "mp_safehouse", "lap_dance_girl" },
		{ LOC("ANIM90"), "mini@strip_club@private_dance@idle", "priv_dance_idle" },
		{ LOC("ANIM91"), "mini@strip_club@private_dance@part2", "priv_dance_p2" },
		{ LOC("ANIM92"), "mini@strip_club@private_dance@part3", "priv_dance_p3" },
		{ LOC("ANIM93"), "switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper" },
		{ LOC("ANIM94"), "amb@world_human_leaning@female@wall@back@hand_up@idle_a", "idle_a" },
		{ LOC("ANIM95"), "random@street_race", "_car_a_flirt_girl" },
		{ LOC("ANIM96"), "mini@repair", "fixing_a_ped" },
		{ LOC("ANIM97"), "rcmcollect_paperleadinout@", "meditiate_idle" },
		{ LOC("ANIM98"), "re@construction", "out_of_breath" },
		{ LOC("ANIM99"), "amb@world_human_push_ups@male@idle_a", "idle_d" },
		{ LOC("ANIM100"), "random@street_race", "grid_girl_race_start" },
		{ LOC("ANIM101"), "gestures@f@standing@casual", "gesture_shrug_hard" },
		{ LOC("ANIM102"), "missfam5_yoga", "a2_pose" },
		{ LOC("ANIM103"), "anim@arena@celeb@flat@paired@no_props@", "laugh_a_player_b" },
		{ LOC("ANIM104"), "mp_player_int_uppergang_sign_a", "mp_player_int_gang_sign_a" },
		{ LOC("ANIM105"), "missarmenian2", "drunk_loop" },
		{ LOC("ANIM106"), "move_injured_ground", "front_loop" },
		{ LOC("ANIM107"), "anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a" },
		{ LOC("ANIM108"), "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a" },
		{ LOC("ANIM109"), "anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a" },
		{ LOC("ANIM110"), "anim@arena@celeb@flat@solo@no_props@", "slide_b_player_a" },
		{ LOC("ANIM111"), "mini@cpr@char_a@cpr_str", "cpr_pumpchest" },
		{ LOC("ANIM112"), "mini@triathlon", "idle_e" },
		{ LOC("ANIM113"), "rcmfanatic1celebrate", "celebrate" },
		{ LOC("ANIM114"), "rcm_barry2", "clown_idle_0" },
		{ LOC("ANIM115"), "amb@world_human_bum_standing@twitchy@idle_a", "idle_c" },
		{ LOC("ANIM127"), "rcmme_tracey1", "nervous_loop" },
		{ LOC("ANIM116"), "timetable@amanda@ig_4", "ig_4_base" },
		{ LOC("ANIM117"), "anim@amb@nightclub@djs@dixon@", "dixn_dance_cntr_open_dix" },
		{ LOC("ANIM118"), "missminuteman_1ig_2", "handsup_base" },
		{ LOC("ANIM121"), "random@arrests@busted", "idle_a" },
		{ LOC("ANIM119"), "rcmnigel1c", "hailing_whistle_waive_a" },
		//{ LOC("ANIM119"), "taxi_hail", "taxi_hail" }, // game seems to automatically cancel this, at least in SP
		{ LOC("ANIM120"), "anim@amb@business@bgen@bgen_no_work@", "stand_phone_phoneputdown_idle_nowork" },
		{ LOC("ANIM122"), "mp_prison_break", "hack_loop" },
		{ LOC("ANIM123"), "amb@world_human_stand_fire@male@idle_a", "idle_a" },
		{ LOC("ANIM124"), "random@hitch_lift", "idle_f" },
		{ LOC("ANIM125"), "anim@arena@celeb@podium@no_prop@", "regal_c_1st" },
		{ LOC("ANIM126"), "rcmbarry", "base" },
		{ LOC("ANIM128"), "anim@amb@carmeet@checkout_car@", "female_c_idle_d" },
		{ LOC("ANIM129"), "mp_safehouseshower@male@", "male_shower_idle_b" },
		{ LOC("ANIM130"), "switch@michael@wash_face", "loop_michael" },
		{ LOC("ANIM131"), "anim@mp_player_intcelebrationfemale@karate_chops", "karate_chops" },
		{ LOC("ANIM132"), "anim@mp_player_intcelebrationmale@shadow_boxing", "shadow_boxing" },
	};

	const std::vector<ComplexDanceAnimation> Animations::dances = {
		ComplexDanceAnimation(LOC("ANIM35"), "anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_11_buttwiggle_b_laz"),
		ComplexDanceAnimation(LOC("ANIM36"), "move_clown@p_m_zero_idles@", "fidget_short_dance"),
		ComplexDanceAnimation(LOC("ANIM37"), "move_clown@p_m_two_idles@", "fidget_short_dance"),
		ComplexDanceAnimation(LOC("ANIM38"), "anim@amb@nightclub@dancers@solomun_entourage@", "mi_dance_facedj_17_v1_female^1"),
		ComplexDanceAnimation(LOC("ANIM39"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center"),
		ComplexDanceAnimation(LOC("ANIM40"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center_up"),
		ComplexDanceAnimation(LOC("ANIM41"), "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^1"),
		ComplexDanceAnimation(LOC("ANIM42"), "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^3"),
		ComplexDanceAnimation(LOC("ANIM43"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "low_center"),
		ComplexDanceAnimation(LOC("ANIM44"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "low_center_down"),
		ComplexDanceAnimation(LOC("ANIM45"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "low_center"),
		ComplexDanceAnimation(LOC("ANIM46"), "anim@amb@nightclub@dancers@podium_dancers@", "hi_dance_facedj_17_v2_male^5"),
		ComplexDanceAnimation(LOC("ANIM47"), "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "high_center_down"),
		ComplexDanceAnimation(LOC("ANIM48"), "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "low_center"),
		ComplexDanceAnimation(LOC("ANIM49"), "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "low_center_down"),
		ComplexDanceAnimation(LOC("ANIM50"), "rcmnigel1bnmt_1b", "dance_loop_tyler"),
		ComplexDanceAnimation(LOC("ANIM51"), "timetable@tracy@ig_5@idle_a", "idle_a"),
		ComplexDanceAnimation(LOC("ANIM52"), "timetable@tracy@ig_8@idle_b", "idle_d"),
		ComplexDanceAnimation(LOC("ANIM53"), "misschinese2_crystalmazemcs1_cs", "dance_loop_tao"),
		ComplexDanceAnimation(LOC("ANIM54"), "anim@mp_player_intcelebrationfemale@the_woogie", "the_woogie"),
		ComplexDanceAnimation(LOC("ANIM166"), "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_center"),
		ComplexDanceAnimation(LOC("ANIM167"), "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_left_down"),
		ComplexDanceAnimation(LOC("ANIM168"), "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_right_up"),
		ComplexDanceAnimation(LOC("ANIM169"), "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_right_down"),
	};

	const std::vector<ComplexObjectAnimation> Animations::object_animations = {
		ComplexObjectAnimation(LOC("ANIM133"), "move_weapon@jerrycan@generic", "idle", ObjectData(ATSTRINGHASH("bkr_prop_biker_case_shut"), PedBoneId::PH_R_Hand, Vector3(0.1000f, 0.0100f, 0.0040f), Vector3(0.0f, 0.0f, -90.0f))),
		ComplexObjectAnimation(LOC("ANIM134"), "amb@world_human_drinking@beer@male@idle_a", "idle_c", ObjectData(ATSTRINGHASH("prop_amb_beer_bottle"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.06f), Vector3(0.0f, 15.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM135"), "amb@world_human_drinking@coffee@male@idle_a", "idle_c", ObjectData(ATSTRINGHASH("v_res_tt_can01"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.00f), Vector3(0.0f, 0.0f, 80.0f))),
		ComplexObjectAnimation(LOC("ANIM136"), "amb@world_human_bum_freeway@male@base", "base", ObjectData(ATSTRINGHASH("prop_beggers_sign_03"), PedBoneId::SKEL_R_Finger20, Vector3(0.19f, 0.18f, 0.00f), Vector3(5.0f, 0.0f, 40.0f))),
		ComplexObjectAnimation(LOC("ANIM137"), "amb@world_human_musician@bongos@male@base", "base", ObjectData(ATSTRINGHASH("prop_bongos_01"), PedBoneId::PH_L_Hand, Vector3(0.0f, 0.0f, 0.00f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM138"), "cellphone@", "cellphone_text_read_base", ObjectData(ATSTRINGHASH("prop_novel_01"), PedBoneId::IK_R_Hand, Vector3(0.15f, 0.03f, -0.065f), Vector3(0.0f, 180.0f, 90.0f))),
		ComplexObjectAnimation(LOC("ANIM139"), "impexp_int-0", "mp_m_waremech_01_dual-0", ObjectData(ATSTRINGHASH("prop_snow_flower_02"), PedBoneId::SKEL_Spine2, Vector3(-0.29f, 0.40f, -0.02f), Vector3(-90.0f, -90.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM140"), "anim@amb@drug_field_workers@rake@male_b@base", "base", ObjectData(ATSTRINGHASH("prop_tool_broom"), PedBoneId::PH_R_Hand, Vector3(-0.0100f, 0.0400f, -0.0300f), Vector3(0.0f, 0.0f, 0.0f)), ForcedMovementType::FORCE_STILL),
		ComplexObjectAnimation(LOC("ANIM141"), "anim@heists@box_carry@", "idle", ObjectData(ATSTRINGHASH("prop_beer_box_01"), PedBoneId::PH_R_Hand, Vector3(0.0200f, -0.0600f, -0.1200f), Vector3(-180.0f, -180.0f, 1.99f))),
		ComplexObjectAnimation(LOC("ANIM142"), "anim@heists@box_carry@", "idle", ObjectData(ATSTRINGHASH("prop_pizza_box_02"), PedBoneId::PH_R_Hand, Vector3(0.0100f, -0.1000f, -0.1590f), Vector3(20.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM143"), "anim@heists@humane_labs@finale@keycards", "ped_a_enter_loop", ObjectData(ATSTRINGHASH("prop_drink_champ"), PedBoneId::SKEL_L_Hand, Vector3(0.10f, -0.03f, 0.03f), Vector3(-100.0f, 0.0f, -10.0f))),
		ComplexObjectAnimation(LOC("ANIM144"), "amb@world_human_drinking@coffee@male@idle_a", "idle_c", ObjectData(ATSTRINGHASH("p_amb_coffeecup_01"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM145"), "move_weapon@jerrycan@generic", "idle", ObjectData(ATSTRINGHASH("bkr_prop_duffel_bag_01a"), PedBoneId::PH_R_Hand, Vector3(0.2600f, 0.0400f, 0.0f), Vector3(90.0f, 0.0f, -78.99f))),
		ComplexObjectAnimation(LOC("ANIM146"), "move_weapon@jerrycan@generic", "idle", ObjectData(ATSTRINGHASH("prop_amb_handbag_01"), PedBoneId::PH_R_Hand, Vector3(0.33f, 0.05f, -0.02f), Vector3(90.4294f, -177.4267f, 83.0011f))),
		ComplexObjectAnimation(LOC("ANIM147"), "amb@world_human_musician@guitar@male@idle_a", "idle_b", ObjectData(ATSTRINGHASH("prop_acc_guitar_01"), PedBoneId::SKEL_Spine3, Vector3(-0.1f, 0.31f, 0.1f), Vector3(0.0f, 20.0f, 150.0f))),
		ComplexObjectAnimation(LOC("ANIM148"), "timetable@trevor@skull_loving_bear", "skull_loving_bear", ObjectData(ATSTRINGHASH("prop_mr_raspberry_01"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM149"), "timetable@reunited@ig_10", "base_amanda", ObjectData(ATSTRINGHASH("prop_skid_chair_02"), PedBoneId::SKEL_ROOT, Vector3(0.025f, 0.0f, -0.15f), Vector3(45.0f, 5.0f, 180.0f)), ForcedMovementType::FORCE_STILL),
		ComplexObjectAnimation(LOC("ANIM150"), "timetable@ron@ig_3_couch", "base", ObjectData(ATSTRINGHASH("prop_skid_chair_02"), PedBoneId::SKEL_ROOT, Vector3(-0.05f, 0.0f, -0.2f), Vector3(5.0f, 0.0f, 180.0f)), ForcedMovementType::FORCE_STILL),
		ComplexObjectAnimation(LOC("ANIM151"), "amb@code_human_in_bus_passenger_idles@female@tablet@idle_a", "idle_a", ObjectData(ATSTRINGHASH("prop_tourist_map_01"), PedBoneId::PH_R_Hand, Vector3(-0.05f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f)), ForcedMovementType::FORCE_MOVEMENT),
		ComplexObjectAnimation(LOC("ANIM152"), "missfinale_c2mcs_1", "fin_c2_mcs_1_camman", ObjectData(ATSTRINGHASH("prop_v_cam_01"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0300f, 0.0100f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM153"), "anim@heists@humane_labs@finale@keycards", "ped_a_enter_loop", ObjectData(ATSTRINGHASH("p_ing_microphonel_01"), PedBoneId::SKEL_L_Finger42, Vector3(0.0f, -0.0200f, 0.1100f), Vector3(0.0f, 0.0f, 60.0f))),
		ComplexObjectAnimation(LOC("ANIM154"), "missbigscore2aleadinout@bs_2a_2b_int", "lester_base_idle", ObjectData(ATSTRINGHASH("prop_cs_walking_stick"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM155"), "cellphone@", "cellphone_call_listen_base", ObjectData(ATSTRINGHASH("prop_phone_proto"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM156"), "random@kidnap_girl", "ig_1_girl_on_phone_loop", ObjectData(ATSTRINGHASH("prop_phone_proto"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM157"), "rcmnigel1d", "base_club_shoulder", ObjectData(ATSTRINGHASH("prop_cs_protest_sign_01"), PedBoneId::SKEL_R_Hand, Vector3(0.1820f, 0.2400f, 0.0600f), Vector3(-69.3774235f, 5.9142048f, -13.95723540f))),
		ComplexObjectAnimation(LOC("ANIM158"), "anim@heists@humane_labs@finale@keycards", "ped_a_enter_loop", ObjectData(ATSTRINGHASH("prop_single_rose"), PedBoneId::SKEL_L_Hand, Vector3(0.13f, 0.15f, 0.0f), Vector3(-100.0f, 0.0f, -20.0f))),
		ComplexObjectAnimation(LOC("ANIM159"), "rcmnigel1d", "base_club_shoulder", ObjectData(ATSTRINGHASH("prop_sign_freewayentrance"), PedBoneId::PH_L_Hand, Vector3(-0.1390f, -0.9870f, 0.4300f), Vector3(-67.3315314f, 145.0627869f, -4.4318885f))),
		ComplexObjectAnimation(LOC("ANIM160"), "rcmnigel1d", "base_club_shoulder", ObjectData(ATSTRINGHASH("prop_sign_road_04a"), PedBoneId::PH_L_Hand, Vector3(-0.1390f, -0.9870f, 0.4300f), Vector3(-67.3315314f, 145.0627869f, -4.4318885f))),
		ComplexObjectAnimation(LOC("ANIM161"), "rcmnigel1d", "base_club_shoulder", ObjectData(ATSTRINGHASH("p_amb_brolly_01_s"), PedBoneId::PH_R_Hand, Vector3(0.0700f, 0.0100f, 0.1100f), Vector3(2.3402393f, -150.9605721f, 57.3374916f))),
		ComplexObjectAnimation(LOC("ANIM162"), "amb@world_human_drinking@coffee@male@idle_a", "idle_c", ObjectData(ATSTRINGHASH("prop_drink_whisky"), PedBoneId::PH_R_Hand, Vector3(0.01f, -0.01f, -0.06f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM163"), "amb@world_human_drinking@beer@male@idle_a", "idle_a", ObjectData(ATSTRINGHASH("ba_prop_battle_whiskey_bottle_2_s"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.05f), Vector3(0.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM164"), "anim@heists@humane_labs@finale@keycards", "ped_a_enter_loop", ObjectData(ATSTRINGHASH("prop_drink_redwine"), PedBoneId::SKEL_L_Hand, Vector3(0.10f, -0.03f, 0.03f), Vector3(-100.0f, 0.0f, -10.0f))),
		ComplexObjectAnimation(LOC("ANIM165"), "amb@world_human_drinking@beer@female@idle_a", "idle_e", ObjectData(ATSTRINGHASH("prop_wine_rose"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.04f, -0.19f), Vector3(10.0f, 0.0f, 0.0f))),
		ComplexObjectAnimation(LOC("ANIM170"), "anim@amb@nightclub_island@dancers@crowddance_single_props@", "hi_dance_prop_09_v1_female^3", ObjectData(ATSTRINGHASH("p_wine_glass_s"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, -0.09f), Vector3(0.0f, 0.0f, 0.0f)), ForcedMovementType::FORCE_STILL),
		ComplexObjectAnimation(LOC("ANIM171"), "anim@amb@nightclub_island@dancers@beachdanceprop@", "mi_idle_c_m01", ObjectData(ATSTRINGHASH("prop_beer_amopen"), PedBoneId::PH_R_Hand, Vector3(0.0f, 0.0f, 0.0f), Vector3(0.0f, 0.0f, 20.0f)), ForcedMovementType::FORCE_STILL),
	};
}