#pragma once

#include "struct_base.hpp"

enum ArchetypeFlags
{
	GTA_MAP_TYPE_WEAPON = BIT(1),
	GTA_MAP_TYPE_MOVER = BIT(2),
	GTA_MAP_TYPE_HORSE = BIT(3),
	GTA_MAP_TYPE_COVER = BIT(4),
	GTA_MAP_TYPE_VEHICLE = BIT(5),

	GTA_VEHICLE_NON_BVH_TYPE = BIT(6),
	GTA_VEHICLE_BVH_TYPE = BIT(7),
	GTA_BOX_VEHICLE_TYPE = BIT(8),
	GTA_PED_TYPE = BIT(9),
	GTA_RAGDOLL_TYPE = BIT(10),
	GTA_HORSE_TYPE = BIT(11),
	GTA_HORSE_RAGDOLL_TYPE = BIT(12),
	GTA_OBJECT_TYPE = BIT(13),
	GTA_ENVCLOTH_OBJECT_TYPE = BIT(14),
	GTA_PLANT_TYPE = BIT(15),

	GTA_PROJECTILE_TYPE = BIT(16),
	GTA_EXPLOSION_TYPE = BIT(17),
	GTA_PICKUP_TYPE = BIT(18),
	GTA_FOLIAGE_TYPE = BIT(19),
	GTA_FORKLIFT_FORKS_TYPE = BIT(20),

	GTA_WEAPON_TEST = BIT(21),
	GTA_CAMERA_TEST = BIT(22),
	GTA_AI_TEST = BIT(23),
	GTA_SCRIPT_TEST = BIT(24),
	GTA_WHEEL_TEST = BIT(25),

	GTA_GLASS_TYPE = BIT(26),
	GTA_RIVER_TYPE = BIT(27),
	GTA_SMOKE_TYPE = BIT(28),
	GTA_UNSMASHED_TYPE = BIT(29),
	GTA_STAIR_SLOPE_TYPE = BIT(30),
	GTA_DEEP_SURFACE_TYPE = BIT(31)
};