#pragma once

#include "gta_fwddecl.hpp"

enum eCarLockState : uint32_t
{
	CARLOCK_NONE = 0x0,
	CARLOCK_UNLOCKED = 0x1,
	CARLOCK_LOCKED = 0x2,
	CARLOCK_LOCKOUT_PLAYER_ONLY = 0x3,
	CARLOCK_LOCKED_PLAYER_INSIDE = 0x4,
	CARLOCK_LOCKED_INITIALLY = 0x5,
	CARLOCK_FORCE_SHUT_DOORS = 0x6,
	CARLOCK_LOCKED_BUT_CAN_BE_DAMAGED = 0x7,
	CARLOCK_LOCKED_BUT_BOOT_UNLOCKED = 0x8,
	CARLOCK_LOCKED_NO_PASSENGERS = 0x9,
	CARLOCK_CANNOT_ENTER = 0xA,
	CARLOCK_PARTIALLY = 0xB,
	CARLOCK_LOCKED_EXCEPT_TEAM1 = 0xC,
	CARLOCK_LOCKED_EXCEPT_TEAM2 = 0xD,
	CARLOCK_LOCKED_EXCEPT_TEAM3 = 0xE,
	CARLOCK_LOCKED_EXCEPT_TEAM4 = 0xF,
	CARLOCK_LOCKED_EXCEPT_TEAM5 = 0x10,
	CARLOCK_LOCKED_EXCEPT_TEAM6 = 0x11,
	CARLOCK_LOCKED_EXCEPT_TEAM7 = 0x12,
	CARLOCK_LOCKED_EXCEPT_TEAM8 = 0x13,
	CARLOCK_NUM_STATES = 0x14,
};