#pragma once

enum eScriptTaskStatus
{
  WAITING_TO_START_TASK = 0,
  PERFORMING_TASK,
  DORMANT_TASK,
  VACANT_STAGE,
  GROUP_TASK_STAGE,
  ATTRACTOR_SCRIPT_TASK_STAGE,
  SECONDARY_TASK_STAGE,
  FINISHED_TASK
};