#pragma once

enum HeistIslandTravelBitset
{
	HITBS__ON_ISLAND,
	HITBS__AT_BEACH_PARTY,
	HITBS__IS_BEACH_PARTY_DISABLED,
	HITBS__IN_WARP_TRANSITION,
	HITBS__IN_WARP_TRIGGER,
	HITBS__RESTRICTED_TO_BEACH_PARTY,
	HITBS__IN_BEACH_PARTY_TO_SCOPING_TRANSITION
};