#pragma once

#define HUD_WANTED_STARS 1
#define HUD_WEAPON_ICON 2
#define HUD_CASH 3
#define HUD_MP_CASH 4
#define HUD_MP_MESSAGE 5
#define HUD_VEHICLE_NAME 6
#define HUD_AREA_NAME 7
#define HUD_VEHICLE_CLASS 8
#define HUD_STREET_NAME 9
#define HUD_HELP_TEXT 10
#define HUD_FLOATING_HELP_TEXT_1 11
#define HUD_FLOATING_HELP_TEXT_2 12
#define HUD_CASH_CHANGE 13
#define HUD_RETICLE 14
#define HUD_SUBTITLE_TEXT 15
#define HUD_RADIO_STATIONS 16
#define HUD_SAVING_GAME 17
#define HUD_GAME_STREAM 18
#define HUD_WEAPON_WHEEL 19
#define HUD_WEAPON_WHEEL_STATS 20
#define MAX_HUD_COMPONENTS 21
#define MAX_HUD_WEAPONS 22
#define MAX_SCRIPTED_HUD_COMPONENTS 141
