#pragma once

#include "atStringHash.hpp"

namespace Stand
{
	enum IncrementableStat : hash_t
	{
		STAT_HELPFUL = ATSTRINGHASH("MPPLY_HELPFUL"), // CWS_HELPFUL
		STAT_FRIENDLY = ATSTRINGHASH("MPPLY_FRIENDLY"), // CWS_FRIENDLY

		STAT_GRIEFING = ATSTRINGHASH("MPPLY_GRIEFING"), // CWS_GRIEFING
		STAT_VC_ANNOYINGME = ATSTRINGHASH("MPPLY_VC_ANNOYINGME"), // RP_VC_ANNOY
		STAT_VC_HATE = ATSTRINGHASH("MPPLY_VC_HATE"), // RP_VC_HATE
		STAT_TC_ANNOYINGME = ATSTRINGHASH("MPPLY_TC_ANNOYINGME"), // RP_TC_ANNOY
		STAT_TC_HATE = ATSTRINGHASH("MPPLY_TC_HATE"), // RP_TC_HATE
		STAT_OFFENSIVE_LANGUAGE = ATSTRINGHASH("MPPLY_OFFENSIVE_LANGUAGE"), // RP_OFFENSIVE_LANGUAGE
		STAT_OFFENSIVE_TAGPLATE = ATSTRINGHASH("MPPLY_OFFENSIVE_TAGPLATE"), // RP_OFFENSIVE_PLATE
		STAT_OFFENSIVE_UGC = ATSTRINGHASH("MPPLY_OFFENSIVE_UGC"), // RP_OFFENSIVE_UGC
		STAT_GAME_EXPLOITS = ATSTRINGHASH("MPPLY_GAME_EXPLOITS"), // RP_GAME_EXPLOIT
		STAT_EXPLOITS = ATSTRINGHASH("MPPLY_EXPLOITS"), // RP_EXPLOITS

		STAT_BAD_CREW_NAME = ATSTRINGHASH("MPPLY_BAD_CREW_NAME"), // RP_CREW_NAME
		STAT_BAD_CREW_MOTTO = ATSTRINGHASH("MPPLY_BAD_CREW_MOTTO"), // RP_MOTTO
		STAT_BAD_CREW_STATUS = ATSTRINGHASH("MPPLY_BAD_CREW_STATUS"), // RP_STATUS
		STAT_BAD_CREW_EMBLEM = ATSTRINGHASH("MPPLY_BAD_CREW_EMBLEM"), // RP_EMBLEM
	};
}
