#pragma once

enum NetScriptWorldStateTypes
{
	NET_WORLD_STATE_FIRST,
	NET_WORLD_STATE_CAR_GEN = NET_WORLD_STATE_FIRST,
	NET_WORLD_STATE_ENTITY_AREA,
	NET_WORLD_STATE_POP_GROUP_OVERRIDE,
	NET_WORLD_STATE_POP_MULTIPLIER_AREA,
	NET_WORLD_STATE_PTFX,
	NET_WORLD_STATE_ROAD_NODE,
	NET_WORLD_STATE_ROPE,
	NET_WORLD_STATE_SCENARIO_BLOCKING_AREA,
	NET_WORLD_STATE_VEHICLE_PLAYER_LOCKING,
	NET_NUM_WORLD_STATES
};
