#pragma once

namespace rage
{
	enum sysLanguage
	{
		LANGUAGE_UNDEFINED = -1,
		LANGUAGE_ENGLISH = 0,
		LANGUAGE_FRENCH,
		LANGUAGE_GERMAN,
		LANGUAGE_ITALIAN,
		LANGUAGE_SPANISH,
		LANGUAGE_PORTUGUESE,
		LANGUAGE_POLISH,
		LANGUAGE_RUSSIAN,
		LANGUAGE_KOREAN,
		LANGUAGE_CHINESE_TRADITIONAL,
		LANGUAGE_JAPANESE,
		LANGUAGE_MEXICAN,
		LANGUAGE_CHINESE_SIMPLIFIED,

		MAX_LANGUAGES
	};
}

using enum rage::sysLanguage;
