#include "weapons.hpp"

#include "atStringHash.hpp"
#include "lang.hpp"
#include "Util.hpp"

namespace Stand
{
	const Weapon Weapon::weapon_unarmed = Weapon{ ATSTRINGHASH("WEAPON_UNARMED"), "WT_UNARMED", "Unarmed", MELEE, ATSTRINGHASH("GROUP_UNARMED")};

	const std::vector<Weapon> Weapon::weapons = {
		// Melee
		Weapon{ATSTRINGHASH("WEAPON_KNIFE"), "WT_KNIFE", "Knife", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_KNUCKLE"), "WT_KNUCKLE", "Knuckle Duster", MELEE, ATSTRINGHASH("GROUP_UNARMED")},
		Weapon{ATSTRINGHASH("WEAPON_NIGHTSTICK"), "WT_NGTSTK", "Nightstick", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_HAMMER"), "WT_HAMMER", "Hammer", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_BAT"), "WT_BAT", "Baseball Bat", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_GOLFCLUB"), "WT_GOLFCLUB", "Golf Club", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_CROWBAR"), "WT_CROWBAR", "Crowbar", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_BOTTLE"), "WT_BOTTLE", "Bottle", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_DAGGER"), "WT_DAGGER", "Antique Cavalry Dagger", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_HATCHET"), "WT_HATCHET", "Hatchet", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_MACHETE"), "WT_MACHETE", "Machete", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_FLASHLIGHT"), "WT_FLASHLIGHT", "Flashlight", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_SWITCHBLADE"), "WT_SWTCHBLDE", "Switchblade", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_POOLCUE"), "WT_POOLCUE", "Pool Cue", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_WRENCH"), "WT_WRENC", "Pipe Wrench", MELEE, ATSTRINGHASH("GROUP_MELEE")}, // There also is WT_WRENCH
		Weapon{ATSTRINGHASH("WEAPON_BATTLEAXE"), "WT_BATTLEAXE", "Battle Axe", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_STONE_HATCHET"), "WT_SHATCHET", "Stone Hatchet", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_CANDYCANE"), "WT_CANDYCANE", "Candy Cane", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		Weapon{ATSTRINGHASH("WEAPON_STUNROD"), "WT_STUNROD", "The Shocker", MELEE, ATSTRINGHASH("GROUP_MELEE")},
		// Throwable
		Weapon{ATSTRINGHASH("WEAPON_GRENADE"), "WT_GNADE", "Grenade", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_GRENADE")},
		Weapon{ATSTRINGHASH("WEAPON_STICKYBOMB"), "WT_GNADE_STK", "Sticky Bomb", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_STICKYBOMB")},
		Weapon{ATSTRINGHASH("WEAPON_PROXMINE"), "WT_PRXMINE", "Proximity Mine", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_PROXMINE")},
		Weapon{ATSTRINGHASH("WEAPON_BZGAS"), "WT_BZGAS", "BZ Gas", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_BZGAS")},
		Weapon{ATSTRINGHASH("WEAPON_SMOKEGRENADE"), "WT_GNADE_SMK", "Tear Gas", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_SMOKEGRENADE")},
		Weapon{ATSTRINGHASH("WEAPON_MOLOTOV"), "WT_MOLOTOV", "Molotov", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_MOLOTOV")},
		Weapon{ATSTRINGHASH("WEAPON_FIREEXTINGUISHER"), "WT_FIRE", "Fire Extinguisher", THROWABLE, ATSTRINGHASH("GROUP_FIREEXTINGUISHER"), ATSTRINGHASH("REWARD_AMMO_FIREEXTINGUISHER")},
		Weapon{ATSTRINGHASH("WEAPON_PETROLCAN"), "WT_PETROL", "Jerry Can", THROWABLE, ATSTRINGHASH("GROUP_PETROLCAN"), ATSTRINGHASH("REWARD_AMMO_PETROLCAN")},
		Weapon{ATSTRINGHASH("WEAPON_SNOWBALL"), "WT_SNWBALL", "Snowball", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_SNOWBALL")},
		Weapon{ATSTRINGHASH("WEAPON_FLARE"), "WT_FLARE", "Flare", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_FLARE")},
		Weapon{ATSTRINGHASH("WEAPON_BALL"), "WT_BALL", "Ball", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_BALL")},
		Weapon{ATSTRINGHASH("WEAPON_PIPEBOMB"), "WT_PIPE", "Pipe Bomb", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_PIPEBOMB")},
		Weapon{ATSTRINGHASH("WEAPON_HAZARDCAN"), "WT_HAZARDCAN", "Hazardous Jerry Can", THROWABLE, ATSTRINGHASH("GROUP_PETROLCAN"), ATSTRINGHASH("REWARD_AMMO_HAZARDCAN")},
		Weapon{ATSTRINGHASH("WEAPON_FERTILIZERCAN"), "WT_FERTCAN", "Fertilizer Can", THROWABLE, ATSTRINGHASH("GROUP_PETROLCAN"), ATSTRINGHASH("REWARD_AMMO_FERTILIZERCAN")},
		Weapon{ATSTRINGHASH("WEAPON_ACIDPACKAGE"), "WT_ACIDPACKAGE", "Acid Package", THROWABLE, ATSTRINGHASH("GROUP_THROWN"), ATSTRINGHASH("REWARD_AMMO_ACIDPACKAGE")},
		// Pistol
		Weapon{ATSTRINGHASH("WEAPON_REVOLVER"), "WT_REVLVR", "Heavy Revolver", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_REVOLVER")}, // There also is WT_REVOLVER
		Weapon{ATSTRINGHASH("WEAPON_PISTOL"), "WT_PIST", "Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_PISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_PISTOL_MK2"), "WT_PIST2", "Pistol Mk II", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_PISTOL_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_COMBATPISTOL"), "WT_PIST_CBT", "Combat Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_COMBATPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_APPISTOL"), "WT_PIST_AP", "AP Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_APPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_PISTOL50"), "WT_PIST_50", "Pistol .50", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_PISTOL50")},
		Weapon{ATSTRINGHASH("WEAPON_SNSPISTOL"), "WT_SNSPISTOL", "SNS Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_SNSPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_HEAVYPISTOL"), "WT_HEAVYPSTL", "Heavy Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_HEAVYPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_VINTAGEPISTOL"), "WT_VPISTOL", "Vintage Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_VINTAGEPISTOL")}, // There also is WT_VINTPSTL
		Weapon{ATSTRINGHASH("WEAPON_STUNGUN"), "WT_STUN", "Stun Gun (SP)", PISTOL, ATSTRINGHASH("GROUP_STUNGUN"), ATSTRINGHASH("REWARD_AMMO_STUNGUN"), ATSTRINGHASH("S_SP")},
		Weapon{ATSTRINGHASH("WEAPON_STUNGUN_MP"), "WT_STUN", "Stun Gun (MP)", PISTOL, ATSTRINGHASH("GROUP_STUNGUN"), ATSTRINGHASH("REWARD_AMMO_STUNGUN_MP"), ATSTRINGHASH("S_MP")},
		Weapon{ATSTRINGHASH("WEAPON_FLAREGUN"), "WT_FLAREGUN", "Flare Gun", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_FLAREGUN")},
		Weapon{ATSTRINGHASH("WEAPON_MARKSMANPISTOL"), "WT_MKPISTOL", "Marksman Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_MARKSMANPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_SNSPISTOL_MK2"), "WT_SNSPISTOL2", "SNS Pistol Mk II", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_SNSPISTOL_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_REVOLVER_MK2"), "WT_REVOLVER2", "Heavy Revolver Mk II", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_REVOLVER_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_DOUBLEACTION"), "WT_REV_DA", "Double-Action Revolver", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_DOUBLEACTION")},
		Weapon{ATSTRINGHASH("WEAPON_RAYPISTOL"), "WT_RAYPISTOL", "Up-n-Atomizer", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_RAYPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_CERAMICPISTOL"), "WT_CERPST", "Ceramic Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_CERAMICPISTOL")},
		Weapon{ATSTRINGHASH("WEAPON_NAVYREVOLVER"), "WT_REV_NV", "Navy Revolver", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_NAVYREVOLVER")},
		Weapon{ATSTRINGHASH("WEAPON_GADGETPISTOL"), "WT_GDGTPST", "Perico Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_GADGETPISTOL")},
		//Weapon{ATSTRINGHASH("WEAPON_METALDETECTOR"), "WT_METALDETECT", PISTOL, ATSTRINGHASH("GROUP_METALDETECTOR"), ATSTRINGHASH("REWARD_AMMO_METALDETECTOR")}, // not really a weapon...
		Weapon{ATSTRINGHASH("WEAPON_PISTOLXM3"), "WT_PISTOLXM3", "WM 29 Pistol", PISTOL, ATSTRINGHASH("GROUP_PISTOL"), ATSTRINGHASH("REWARD_AMMO_PISTOLXM3")},
		// SMGs
		Weapon{ATSTRINGHASH("WEAPON_MICROSMG"), "WT_SMG_MCR", "Micro SMG", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_MICROSMG")},
		Weapon{ATSTRINGHASH("WEAPON_MACHINEPISTOL"), "WT_MCHPIST", "Machine Pistol", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_MACHINEPISTOL")}, // There also is WT_MACHPIST
		Weapon{ATSTRINGHASH("WEAPON_MINISMG"), "WT_MINISMG", "Mini SMG", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_MINISMG")},
		Weapon{ATSTRINGHASH("WEAPON_SMG"), "WT_SMG", "SMG", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_SMG")},
		Weapon{ATSTRINGHASH("WEAPON_SMG_MK2"), "WT_SMG2", "SMG Mk II", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_SMG_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_ASSAULTSMG"), "WT_SMG_ASL", "Assault SMG", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_ASSAULTSMG")},
		Weapon{ATSTRINGHASH("WEAPON_MG"), "WT_MG", "MG", SMG, ATSTRINGHASH("GROUP_MG"), ATSTRINGHASH("REWARD_AMMO_MG")},
		Weapon{ATSTRINGHASH("WEAPON_COMBATMG"), "WT_MG_CBT", "Combat MG", SMG, ATSTRINGHASH("GROUP_MG"), ATSTRINGHASH("REWARD_AMMO_COMBATMG")},
		Weapon{ATSTRINGHASH("WEAPON_COMBATMG_MK2"), "WT_MG_CBT2", "Combat MG Mk II", SMG, ATSTRINGHASH("GROUP_MG"), ATSTRINGHASH("REWARD_AMMO_COMBATMG_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_RAYCARBINE"), "WT_RAYCARBINE", "Unholy Hellbringer", SMG, ATSTRINGHASH("GROUP_MG"), ATSTRINGHASH("REWARD_AMMO_RAYCARBINE")},
		Weapon{ATSTRINGHASH("WEAPON_COMBATPDW"), "WT_COMBATPDW", "Combat PDW", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_COMBATPDW")},
		Weapon{ATSTRINGHASH("WEAPON_GUSENBERG"), "WT_GUSENBERG", "Gusenberg Sweeper", SMG, ATSTRINGHASH("GROUP_MG"), ATSTRINGHASH("REWARD_AMMO_GUSENBERG")},
		Weapon{ATSTRINGHASH("WEAPON_TECPISTOL"), "WT_TECPISTOL", "Tactical SMG", SMG, ATSTRINGHASH("GROUP_SMG"), ATSTRINGHASH("REWARD_AMMO_TECPISTOL")}, // guessed reward name
		// Rifles
		Weapon{ATSTRINGHASH("WEAPON_ASSAULTRIFLE"), "WT_RIFLE_ASL", "Assault Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_ASSAULTRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_ASSAULTRIFLE_MK2"), "WT_RIFLE_ASL2", "Assault Rifle Mk II", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_ASSAULTRIFLE_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_CARBINERIFLE"), "WT_RIFLE_CBN", "Carbine Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_CARBINERIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_CARBINERIFLE_MK2"), "WT_RIFLE_CBN2", "Carbine Rifle Mk II", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_CARBINERIFLE_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_ADVANCEDRIFLE"), "WT_RIFLE_ADV", "Advanced Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_ADVANCEDRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_SPECIALCARBINE"), "WT_RIFLE_SCBN", "Special Carbine", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_SPECIALCARBINE")},
		Weapon{ATSTRINGHASH("WEAPON_SPECIALCARBINE_MK2"), "WT_SPCARBINE2", "Special Carbine Mk II", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_SPECIALCARBINE_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_BULLPUPRIFLE"), "WT_BULLPUPRFL", "Bullpup Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_BULLPUPRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_BULLPUPRIFLE_MK2"), "WT_BULLRIFLE2", "Bullpup Rifle Mk II", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_BULLPUPRIFLE_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_COMPACTRIFLE"), "WT_CMPRIFLE", "Compact Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_COMPACTRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_MILITARYRIFLE"), "WT_MLTRYRFL", "Military Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_MILITARYRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_HEAVYRIFLE"), "WT_HEAVYRIFLE", "Heavy Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_HEAVYRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_TACTICALRIFLE"), "WT_TACRIFLE", "Service Carbine", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_TACTICALRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_BATTLERIFLE"), "WT_BATTLERIFLE", "Battle Rifle", RIFLE, ATSTRINGHASH("GROUP_RIFLE"), ATSTRINGHASH("REWARD_AMMO_BATTLERIFLE")},
		// Shotguns
		Weapon{ATSTRINGHASH("WEAPON_PUMPSHOTGUN"), "WT_SG_PMP", "Pump Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_PUMPSHOTGUN"), 0, 8},
		Weapon{ATSTRINGHASH("WEAPON_PUMPSHOTGUN_MK2"), "WT_SG_PMP2", "Pump Shotgun Mk II", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_PUMPSHOTGUN_MK2"), 0, 8},
		Weapon{ATSTRINGHASH("WEAPON_AUTOSHOTGUN"), "WT_AUTOSHOT", "Sweeper Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_AUTOSHOTGUN"), 0, 6},
		Weapon{ATSTRINGHASH("WEAPON_SAWNOFFSHOTGUN"), "WT_SG_SOF", "Sawed-Off Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_SAWNOFFSHOTGUN"), 0, 8},
		Weapon{ATSTRINGHASH("WEAPON_BULLPUPSHOTGUN"), "WT_SG_BLP", "Bullpup Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_BULLPUPSHOTGUN"), 0, 8},
		Weapon{ATSTRINGHASH("WEAPON_ASSAULTSHOTGUN"), "WT_SG_ASL", "Assault Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_ASSAULTSHOTGUN"), 0, 6},
		Weapon{ATSTRINGHASH("WEAPON_MUSKET"), "WT_MUSKET", "Musket", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_MUSKET"), 0, 1},
		Weapon{ATSTRINGHASH("WEAPON_HEAVYSHOTGUN"), "WT_HVYSHOT", "Heavy Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_HEAVYSHOTGUN"), 0, 1},
		Weapon{ATSTRINGHASH("WEAPON_DBSHOTGUN"), "WT_DBSHGN", "Double Barrel Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_DBSHOTGUN"), 0, 8},
		Weapon{ATSTRINGHASH("WEAPON_COMBATSHOTGUN"), "WT_CMBSHGN", "Combat Shotgun", SHOTGUN, ATSTRINGHASH("GROUP_SHOTGUN"), ATSTRINGHASH("REWARD_AMMO_COMBATSHOTGUN"), 0, 6},
		// Sniper Rifles
		Weapon{ATSTRINGHASH("WEAPON_SNIPERRIFLE"), "WT_SNIP_RIF", "Sniper Rifle", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_SNIPERRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_HEAVYSNIPER"), "WT_SNIP_HVY", "Heavy Sniper", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_HEAVYSNIPER")},
		Weapon{ATSTRINGHASH("WEAPON_HEAVYSNIPER_MK2"), "WT_SNIP_HVY2", "Heavy Sniper Mk II", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_HEAVYSNIPER_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_MARKSMANRIFLE"), "WT_MKRIFLE", "Marksman Rifle", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_MARKSMANRIFLE")},
		Weapon{ATSTRINGHASH("WEAPON_MARKSMANRIFLE_MK2"), "WT_MKRIFLE2", "Marksman Rifle Mk II", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_MARKSMANRIFLE_MK2")},
		Weapon{ATSTRINGHASH("WEAPON_PRECISIONRIFLE"), "WT_PRCSRIFLE", "Precision Rifle", SNIPER, ATSTRINGHASH("GROUP_SNIPER"), ATSTRINGHASH("REWARD_AMMO_PRECISIONRIFLE")},
		// Heavy
		Weapon{ATSTRINGHASH("WEAPON_GRENADELAUNCHER"), "WT_GL", "Grenade Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_GRENADELAUNCHER")}, // Maybe "REWARD_AMMO_GRENADELAUNCHER_MP" ?
		Weapon{ATSTRINGHASH("WEAPON_RPG"), "WT_RPG", "RPG", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_RPG")},
		Weapon{ATSTRINGHASH("WEAPON_MINIGUN"), "WT_MINIGUN", "Minigun", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_MINIGUN")},
		Weapon{ATSTRINGHASH("WEAPON_FIREWORK"), "WT_FWRKLNCHR", "Firework Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_FIREWORK")}, // There's also "REWARD_AMMO_FIREWORK_MP" but this seems to work fine
		Weapon{ATSTRINGHASH("WEAPON_RAILGUN"), "WT_RAILGUN", "Railgun (SP)", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_RAILGUN"), ATSTRINGHASH("S_SP")},
		Weapon{ATSTRINGHASH("WEAPON_RAILGUNXM3"), "WT_RAILGUNXM3", "Railgun (MP)", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_RAILGUNXM3"), ATSTRINGHASH("S_MP")},
		Weapon{ATSTRINGHASH("WEAPON_RAYMINIGUN"), "WT_RAYMINIGUN", "Widowmaker", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_RAYMINIGUN")},
		Weapon{ATSTRINGHASH("WEAPON_HOMINGLAUNCHER"), "WT_HOMLNCH", "Homing Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_HOMINGLAUNCHER")},
		Weapon{ATSTRINGHASH("WEAPON_COMPACTLAUNCHER"), "WT_CMPLAUNC", "Compact Grenade Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_COMPACTLAUNCHER")},
		Weapon{ATSTRINGHASH("WEAPON_EMPLAUNCHER"), "WT_EMPL", "Compact EMP Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_EMPLAUNCHER")},
		//Weapon{ATSTRINGHASH("WEAPON_STINGER"), "WT_RPG", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_STINGER")}, // Weird RPG clone
		Weapon{ATSTRINGHASH("WEAPON_SNOWLAUNCHER"), "WT_SNOWLNCHR", "Snowball Launcher", HEAVY, ATSTRINGHASH("GROUP_HEAVY"), ATSTRINGHASH("REWARD_AMMO_SNOWLAUNCHER")},
	};

	std::string Weapon::getDisplayName() const
	{
		return Util::GET_LABEL_TEXT(label_hash_name, false);
	}

	std::string Weapon::getName() const
	{
		auto name = getDisplayName();
		if (disambiguator != 0)
		{
			name.append(" (");
			name.append(Lang::get(disambiguator));
			name.push_back(')');
		}
		return name;
	}

	std::string Weapon::getCategoryName() const
	{
		return getCategoryName(category);
	}

	const Weapon* Weapon::find(const hash_t hash)
	{
		for (const auto& weapon : weapons)
		{
			if (weapon.hash == hash)
			{
				return &weapon;
			}
		}
		return nullptr;
	}

	std::vector<hash_t> Weapon::getAllHashes()
	{
		std::vector<hash_t> all{};
		all.reserve(Weapon::weapons.size());
		for (const auto& weapon : Weapon::weapons)
		{
			all.emplace_back(weapon.hash);
		}
		return all;
	}

	std::vector<hash_t> Weapon::getAllHashesIncludingWeirdos()
	{
		auto all = getAllHashes();
		all.emplace_back(ATSTRINGHASH("WEAPON_GRENADELAUNCHER_SMOKE"));
		all.emplace_back(ATSTRINGHASH("WEAPON_METALDETECTOR"));
		all.emplace_back(ATSTRINGHASH("WEAPON_STINGER"));
		all.emplace_back(ATSTRINGHASH("WEAPON_TRANQUILIZER"));
		all.emplace_back(ATSTRINGHASH("WEAPON_HACKINGDEVICE"));
		return all;
	}

	bool Weapon::isValidHash(hash_t hash)
	{
		for (const auto& w : getAllHashesIncludingWeirdos())
		{
			if (w == hash)
			{
				return true;
			}
		}
		return false;
	}

	std::string Weapon::getCategoryName(Category cat) noexcept
	{
		switch (cat)
		{
		case THROWABLE:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("AT_THROW"));
		case PISTOL:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_9"));
		case SMG:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_3"));
		case RIFLE:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_4"));
		case SHOTGUN:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_2"));
		case SNIPER:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_5"));
		case HEAVY:
			return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_6"));
		}
		return Util::GET_LABEL_TEXT_no_replacements(ATSTRINGHASH("VAULT_WMENUI_8"));
	}

	const char* Weapon::getCategoryAmericanName(Category cat) noexcept
	{
		switch (cat)
		{
		case THROWABLE:
			return "Throwables";
		case PISTOL:
			return "Pistols";
		case SMG:
			return "Machine Guns";
		case RIFLE:
			return "Rifles";
		case SHOTGUN:
			return "Shotguns";
		case SNIPER:
			return "Sniper Rifles";
		case HEAVY:
			return "Heavy Weapons";
		}
		return "Melee Weapons";
	}

	static const char* category_strings[] = {
		"MELEE",
		"THROWABLE",
		"PISTOL",
		"SMG",
		"RIFLE",
		"SHOTGUN",
		"SNIPER",
		"HEAVY",
	};

	const char* Weapon::categoryToString(Category cat) noexcept
	{
		return category_strings[cat];
	}
}
